---
name: WhaleAlert
version: 1.0.2
main: XanderID\WhaleAlert\WhaleAlert
api: 4.0.0
author: XanderID
description: a Plugin Alert for Big pay Transaction Economys
softdepend:
 - BedrockEconomy
 - EconomyAPI

permissions:
 whalealert.toggle:
  default: true
  description: Toggle On/Off Whale Alert
...
